import os
from pathlib import Path

import pytest


@pytest.fixture(scope="session", autouse=True)
def app_home(tmp_path_factory):
    """Isolate per-user app dirs (thumbs/chroma/logs) into a throwaway home."""
    home = tmp_path_factory.mktemp("imgsearch_home")
    os.environ["IMGSEARCH_HOME"] = str(home)
    return home


@pytest.fixture(scope="session")
def sample_ds(tmp_path_factory) -> Path:
    from imgsearch.sample_data import generate_sample_dataset

    root = tmp_path_factory.mktemp("ds")
    return generate_sample_dataset(root, per_scene=3)


@pytest.fixture(scope="session")
def n_scenes() -> int:
    """Number of leaf folders generated by sample_data."""
    return 8
